Repository GeoNet/delta, pull requests merged in 2018-06, with the labels that each got.

#306 add channel naming documentation
  docs/CHANNELS.md
Labels: enhancement

#319 update TENN and TEN2 coordinates
  network/marks.csv
Labels: bug

#174 add helper sheets
  docs/sheets/ASSETS.md
  docs/sheets/CAMERA.md
  docs/sheets/GNSS.md
  docs/sheets/RECORDING.md
Labels: enhancement, help wanted

#313 add metadata notes imported from RT ticket
  environment/visibility.csv
  install/sessions.csv
Labels: After db
