Repository GeoNet/delta, pull requests merged in 2018-04, with the labels that each got.

#262 PWZ station is Open Now. It was missing.
  network/stations.csv
Labels: bug

#263 added site stream time checks
  README.md
  tests/README.md
  tests/delta.go
  tests/sites_test.go
  tests/stations_test.go
  tests/streams_test.go
Labels: After db

#265 remove unnecessary duplicate GNSS sessions
  install/firmware.csv
  install/sessions.csv
Labels: After db

#266 update all full-GNSS sites on session file
  install/sessions.csv
Labels: After db

#258 BWHS reoccupy
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: bug, enhancement

#270 remove RCHD entries, never became a site
  environment/visibility.csv
  network/marks.csv
  network/monuments.csv
Labels: After db
