Repository GeoNet/delta, pull requests merged in 2018-07, with the labels that each got.

#331 add old firmware entry for WGTN GNSS station
  install/firmware.csv
Labels: After db

#333 insert antenna entry to WGTN to match with radome install
  install/antennas.csv
  install/radomes.csv
Labels: After db

#299 RBCT new sensors
  assets/sensors.csv
  install/sensors.csv
Labels: help wanted

#352 reverse the FIR filter factors for Q330+ streams
  resp/auto.go
  resp/responses/filters/quanterra.yaml
  tools/stationxml/testdata/test.xml
Labels: bug
