Repository GeoNet/delta, pull requests merged in 2019-08, with the labels that each got.

#581 Updated datalogger connections mapping.
  install/connections.csv
  install/dataloggers.csv
  tests/connections_test.go
Labels: After db

#583 MRZ continuous 200 Hz are No more Triggerred
  install/streams.csv
Labels: bug

#585 ECLS -East cape - XX to SM (permanent station input)
  network/stations.csv
Labels: enhancement, question
