Repository GeoNet/delta, pull requests merged in 2019-09, with the labels that each got.

#592 TMHS 21 is 12Z Not axial ENZ
  install/streams.csv
Labels: bug

#600 updated sc3 tool
  tools/sc3/autopick.go
  tools/sc3/autopick_test.go
  tools/sc3/global.go
  tools/sc3/global_test.go
  tools/sc3/main.go
  tools/sc3/profile.go
  tools/sc3/station.go
  tools/sc3/station_test.go
Labels: enhancement, help wanted

#599 add caps tool
  tools/caps/main.go
  tools/caps/station_test.go
Labels: enhancement

#603 updated output file locations
  tools/sc3/autopick.go
  tools/sc3/global.go
  tools/sc3/profile.go
Labels: enhancement

#608 added ISO version of episensor to obsidian response list
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
Labels: enhancement

#616 Remove 2020 stations outdated placeholders
  network/stations.csv
Labels: enhancement
