Repository GeoNet/delta, pull requests merged in 2021-01, with the labels that each got.

#982 updated pod export for nanometrics sensors
  tools/pod/blockette.go
  tools/pod/pod.go
Labels: bug

#987 OUZ VH 0.1 stream Closed in 2010.054
  install/streams.csv
Labels: After db

#988 SOMS HN to continuous 200Hz
  install/streams.csv
Labels: enhancement

#986 CMWZ strong motion Not axial since 2016 and Continuous 200Hz in 2020
  install/streams.csv
Labels: enhancement

#991 Last 0.1 Hz VH channel closure QRZ/BFZ
  install/streams.csv
Labels: enhancement
