Repository GeoNet/delta, pull requests merged in 2022-08, with the labels that each got.

#1419 A11 temp seismic station is EH not SH short period
  install/streams.csv
Labels: bug

#1421 Guralp Fortis - fixed .yaml indent
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
Labels: bug

#1423 EARSS short period 100Hz configuration (90's)
  resp/auto.go
  resp/responses/configurations/shortperiod.yaml
Labels: enhancement

#1395 rename gains and features columns to be consistent with streams
  environment/README.md
  environment/features.csv
  install/README.md
  install/gains.csv
  internal/metadb/gains.go
  meta/feature.go
  meta/gain.go
  meta/list_test.go
  meta/testdata/features.csv
  meta/testdata/gains.csv
  tests/features_test.go
  tests/gains_test.go
Labels: enhancement, stationxml

#1429 the camera config code is no longer needed
  cmd/camera-config/README.md
  cmd/camera-config/caption.go
  cmd/camera-config/caption_test.go
  cmd/camera-config/main.go
  cmd/volcam-config/README.md
  cmd/volcam-config/main.go
  cmd/volcam-config/volcam.go
  cmd/volcam-config/volcam_test.go
Labels: debt

#1394 Stationxml streams
  install/README.md
  install/streams.csv
  meta/list_test.go
  meta/streams.go
  meta/testdata/streams.csv
  tools/altus/testdata/install/streams.csv
  tools/amplitude/testdata/install/streams.csv
  tools/chart/testdata/install/streams.csv
  tools/cusp/testdata/install/streams.csv
  tools/impact/testdata/install/streams.csv
  tools/spectra/testdata/install/streams.csv
  tools/stationxml/testdata/install/streams.csv
Labels: enhancement, stationxml
