Repository GeoNet/delta, pull requests merged in 2022-02, with the labels that each got.

#1268 fix equipment sort order for capitals
  install/recorders.csv
  install/sensors.csv
  meta/meta.go
Labels: bug

#1274 Fix WVZ strong motion datalogger stream 20 End (2011)
  install/dataloggers.csv
Labels: bug

#1275 BFZ Metadata correction to match orphan data 2015 and 2021
  install/dataloggers.csv
  install/sensors.csv
Labels: enhancement

#1226 Kinemetrics Obsidian 4X response correction
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
  resp/responses/dataloggers/kinemetrics.yaml
Labels: enhancement

#1276 Dart Deploy meta update
  install/streams.csv
  network/sites.csv
  network/stations.csv
Labels: enhancement, question
