Repository GeoNet/delta, pull requests merged in 2022-12, with the labels that each got.

#1560 remove manually collected samples from stations.csv
  network/stations.csv
Labels: enhancement

#1557 small updates to QRZ/EPAZ/HBAZ
  install/preamps.csv
  install/streams.csv
Labels: bug, stationxml, maintenance

#1563 update responses for Q330S 10Hz and derived responses
  meta/collection.go
  resp/auto.go
  resp/auto/datalogger_Kinemetrics_Q330S_24bits_10sps.xml
  resp/responses/dataloggers/quanterra.yaml
Labels: bug

#1564 update tests to remove exec call, replace with cmp
  tools/altus/altus_test.go
  tools/amplitude/amplitude_test.go
  tools/chart/chart_test.go
  tools/cusp/cusp_test.go
  tools/impact/impact_test.go
  tools/rinexml/site_test.go
  tools/spectra/spectra_test.go
  tools/stationxml/build_test.go
Labels: maintenance

#1565 replace ioutil module
  meta/list_test.go
  resp/generate/main.go
  tests/consistency_test.go
  tools/altus/altus_test.go
  tools/altus/main.go
  tools/amplitude/amplitude_test.go
  tools/amplitude/config.go
  tools/amplitude/main.go
  tools/caps/main.go
  tools/caps/station_test.go
  tools/chart/chart_test.go
  tools/chart/config.go
  tools/chart/main.go
  tools/cusp/cusp_test.go
  tools/cusp/main.go
  tools/gloria/main.go
  tools/impact/impact_test.go
  tools/impact/main.go
  tools/pod/main.go
  tools/pod/pod.go
  tools/rinexml/main.go
  tools/sc3/autopick_test.go
  tools/sc3/global_test.go
  tools/sc3/profile.go
  tools/sc3/station_test.go
  tools/sit/main.go
  tools/sitelogs/generate/main.go
  tools/sitelogs/main.go
  tools/sitelogs/sitelog_test.go
  tools/sitelogs/txt_file.go
  tools/spectra/config.go
  tools/spectra/main.go
  tools/spectra/spectra_test.go
  tools/stationxml/build_test.go
  tools/stationxml/main.go
  tools/tide/main.go
Labels: maintenance

#1571 Add PTX-1830-LAND w/ Centaur for derived fresh water depth
  resp/auto.go
  resp/responses/configurations/pressure.yaml
Labels: enhancement
