Repository GeoNet/delta, pull requests merged in 2022-05, with the labels that each got.

#1354 updated visibility checks
  environment/visibility.csv
  tests/consistency_test.go
Labels: bug, gnss

#1352 add placenames environment table
  environment/README.md
  environment/placenames.csv
  meta/list_test.go
  meta/placenames.go
  meta/testdata/placenames.csv
  tests/placenames_test.go
Labels: enhancement, stationxml

#1362 CPLB loc 22 irrelevant SM streams - Only BN 50 and HN 200Hz exist
  install/streams.csv
Labels: after db
