Repository GeoNet/delta, pull requests merged in 2023-09, with the labels that each got.

#1828 feat: expand dart table to be a replacement for dart values in stations
  meta/dart.go
  meta/dart_test.go
  meta/generate/main.go
  meta/set.go
  meta/set_auto.go
  meta/testdata/darts.csv
  tests/darts_test.go
Labels: dart

#1830 feat: remove travis code from repo
  .travis.yml
  README.md
  run/deploy/10-ac-tools-trigger.sh
Labels: debt

#1834 feat: update actions tests order
  .github/workflows/build.yml
Labels: enhancement

#1833 feat: update bnc and ntripcaster config apps
  cmd/bnc-config/build.go
  cmd/bnc-config/config.go
  cmd/bnc-config/config_test.go
  cmd/bnc-config/main.go
  cmd/bnc-config/testdata/aliases.csv
  cmd/bnc-config/testdata/config.yaml
  cmd/bnc-config/testdata/formats.csv
  cmd/bnc-config/testdata/models.csv
  cmd/bnc-config/testdata/mounts.csv
  cmd/bnc-config/testdata/network/marks.csv
  cmd/bnc-config/testdata/users.csv
  cmd/ntripcaster-config/build.go
  cmd/ntripcaster-config/config.go
  cmd/ntripcaster-config/config_test.go
  cmd/ntripcaster-config/main.go
  cmd/ntripcaster-config/testdata/aliases.csv
  cmd/ntripcaster-config/testdata/config.yaml
  cmd/ntripcaster-config/testdata/formats.csv
  cmd/ntripcaster-config/testdata/install/receivers.csv
  cmd/ntripcaster-config/testdata/models.csv
  cmd/ntripcaster-config/testdata/mounts.csv
  cmd/ntripcaster-config/testdata/network/marks.csv
  cmd/ntripcaster-config/testdata/users.csv
  internal/ntrip/README.md
  internal/ntrip/alias.go
  internal/ntrip/file.go
  internal/ntrip/file_test.go
  internal/ntrip/format.go
  internal/ntrip/model.go
  internal/ntrip/mount.go
  internal/ntrip/ntrip.go
  internal/ntrip/testdata/aliases.csv
  internal/ntrip/testdata/formats.csv
  internal/ntrip/testdata/models.csv
  internal/ntrip/testdata/mounts.csv
  internal/ntrip/testdata/users.csv
  internal/ntrip/user.go
Labels: enhancement, gnss

#1835 feat: add simple ndbc dart status app
  cmd/ndbc-update/deployment.go
  cmd/ndbc-update/main.go
  cmd/ndbc-update/template.go
Labels: enhancement, dart

#1841 fix: required to split out common ntrip files
  cmd/bnc-config/build.go
  cmd/bnc-config/config.go
  cmd/bnc-config/config_test.go
  cmd/bnc-config/main.go
  cmd/ntripcaster-config/build.go
  cmd/ntripcaster-config/config.go
  cmd/ntripcaster-config/config_test.go
  cmd/ntripcaster-config/main.go
  internal/ntrip/ntrip.go
Labels: bug, enhancement

#1842 feat: add camera config apps
  cmd/camera-config/caption.go
  cmd/camera-config/caption_test.go
  cmd/camera-config/main.go
  cmd/volcam-config/main.go
  cmd/volcam-config/volcam.go
  cmd/volcam-config/volcam_test.go
Labels: enhancement, debt

#1843 feat: add sc3 config apps
  cmd/caps-config/main.go
  cmd/caps-config/station.go
  cmd/caps-config/station_test.go
  cmd/sc3-config/autopick.go
  cmd/sc3-config/autopick_test.go
  cmd/sc3-config/global.go
  cmd/sc3-config/global_test.go
  cmd/sc3-config/main.go
  cmd/sc3-config/profile.go
  cmd/sc3-config/station.go
  cmd/sc3-config/station_test.go
Labels: enhancement

#1844 feat: add extra apps
  cmd/dart-config/config.go
  cmd/dart-config/detide.go
  cmd/dart-config/main.go
  cmd/tilde-config/coastal.go
  cmd/tilde-config/dart.go
  cmd/tilde-config/envirosensor.go
  cmd/tilde-config/main.go
  cmd/tilde-config/manualcollect.go
  cmd/tilde-config/testdata/tilde.xml
  cmd/tilde-config/tilde.go
  cmd/tilde-config/tilde_test.go
Labels: enhancement

#1845 feat: add lrdcp config app
  cmd/lrdcp-config/lrdcp.go
  cmd/lrdcp-config/main.go
Labels: enhancement

#1823 fix: update ABAZ streams
  install/connections.csv
  install/sensors.csv
  install/streams.csv
  network/sites.csv
Labels: bug

#1854 fix: correct the handling of single files
  cmd/stationxml-build/main.go
Labels: bug

#1846 fix: added serial number of bpr sensor to ndbc-update
  cmd/ndbc-update/main.go
  cmd/ndbc-update/template.go
Labels: enhancement

#1858 chore: swap point with position
  meta/gauge.go
  meta/headers_test.go
  meta/list_test.go
  meta/mark.go
  meta/meta.go
  meta/metsensor.go
  meta/mount.go
  meta/sample.go
  meta/samples_test.go
  meta/site.go
  meta/station.go
Labels: enhancement

#1747 geomag: add SMHS partial metadata
  assets/sensors.csv
  install/channels.csv
  install/components.csv
  install/connections.csv
  install/sensors.csv
  install/streams.csv
  network/sites.csv
Labels: geomag

#1856 feat: add points to separate manually collected data from sites.csv
  network/README.md
  network/points.csv
Labels: enhancement

#1852 add new GNSS site MNMW
  environment/visibility.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss
