Repository GeoNet/delta, pull requests merged in 2023-02, with the labels that each got.

#1620 un-reverse qrz
  install/streams.csv
Labels: bug

#1619 add telemetry stages
  internal/stationxml/response.go
Labels: enhancement, stationxml

#1621 add CUSPM and CUSP-Me
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
  resp/responses/dataloggers/cusp.yaml
  resp/responses/sensors/cusp.yaml
Labels: enhancement

#1623 add 50Hz Cusp-Me resp
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
Labels: enhancement

#1584 add stationxml encode elements
  internal/stationxml/encoder.go
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
Labels: enhancement

#1606 New Nanometrics Titan Accelerometer TACCL-N1 (standalone) and Titan Borehole Accelerometer TACCL-BH1
  assets/sensors.csv
Labels: enhancement
