Repository GeoNet/delta, pull requests merged in 2023-05, with the labels that each got.

#1691 add changed option to stationxml-build
  cmd/stationxml-build/main.go
Labels: stationxml

#1695 Hydrophone array Delta datalogger Q330/6 configuration
  resp/auto.go
  resp/responses/configurations/hydrophone.yaml
Labels: enhancement

#1701 add Titan N1 to components list
  install/components.csv
Labels: bug, stationxml, strong, maintenance

#1704 use Guralp as manufacturer (Make)
  assets/dataloggers.csv
  assets/sensors.csv
  install/components.csv
  install/sensors.csv
  tools/amplitude/testdata/install/sensors.csv
  tools/spectra/testdata/install/sensors.csv
Labels: stationxml

#1705 update manufacturer (Make) from CSI to Cant Seism Instr
  assets/recorders.csv
  install/channels.csv
  install/components.csv
  install/firmware.csv
  install/recorders.csv
  meta/list_test.go
  meta/testdata/recorders.csv
  resp/auto.go
  resp/responses/configurations/strongmotion.yaml
  resp/responses/dataloggers/cusp.yaml
  tools/cusp/testdata/install/recorders.csv
  tools/impact/testdata/install/recorders.csv
  tools/pod/blockette.go
  tools/pod/pod.go
Labels: stationxml

#1706 update manufacturer (Make) General Electric
  assets/sensors.csv
  install/components.csv
  install/sensors.csv
  meta/testdata/manufacturers.csv
  meta/testdata/models.csv
  resp/auto.go
  resp/auto/sensor_General-Electric_Druck-PTX-1830-LAND.xml
  resp/auto/sensor_General-Electric_Druck-PTX-1830.xml
  resp/responses/sensors/druck.yaml
  tools/chart/testdata/install/sensors.csv
Labels: stationxml

#1710 update manufacturer (Make) Lennartz and Streckeisen
  assets/dataloggers.csv
  assets/sensors.csv
  install/components.csv
  install/dataloggers.csv
  install/sensors.csv
  resp/README.md
  resp/auto.go
  resp/responses/sensors/lennartz.yaml
  tools/pod/blockette.go
  tools/pod/pod.go
Labels: stationxml

#1712 revert manufacturer (Make) name of GNS to remove macron
  assets/dataloggers.csv
  assets/sensors.csv
  install/channels.csv
  install/components.csv
  install/connections.csv
  install/dataloggers.csv
  install/sensors.csv
  meta/list_test.go
  meta/testdata/dataloggers.csv
  resp/responses/dataloggers/gns.yaml
  resp/responses/sensors/gns.yaml
Labels: stationxml

#1715 update manufacturer (Make) Nanometrics
  assets/dataloggers.csv
  assets/sensors.csv
  install/components.csv
  install/sensors.csv
  resp/responses/sensors/nanometrics.yaml
Labels: stationxml

#1716 update hydrophone
  resp/auto.go
  resp/responses/configurations/hydrophone.yaml
Labels: bug

#1700 update delta testing to use set
  tests/antennas_test.go
  tests/assets_test.go
  tests/calibrations_test.go
  tests/cameras_test.go
  tests/combined_test.go
  tests/connections_test.go
  tests/consistency_test.go
  tests/constituents_test.go
  tests/dataloggers_test.go
  tests/doases_test.go
  tests/firmware_test.go
Labels: enhancement, debt

#1717 update resp
  resp/auto.go
  resp/auto/sensor_Nanometrics_Titan-TACCL-BH1.xml
  resp/auto/sensor_Nanometrics_Titan-TACCL-N1.xml
  resp/auto/sensor_Nanometrics_Titan.xml
  resp/auto/sensor_Nanometrics_Trillium-120QA.xml
  resp/auto/sensor_Nanometrics_Trillium-360.xml
  resp/auto/sensor_Nanometrics_Trillium-Borehole-T120-BH1.xml
  resp/auto/sensor_Nanometrics_Trillium-Compact-120.xml
  resp/auto/sensor_Nanometrics_Trillium-Compact-120PH-2.xml
  resp/auto/sensor_Nanometrics_Trillium-Compact-20PH-2.xml
  resp/auto/sensor_Nanometrics_Trillium-Horizon-TH120-1.xml
  resp/auto/sensor_Nanometrics_Trillium-Horizon-TH120-2.xml
Labels: stationxml, maintenance

#1721 update mic reference frequency
  resp/auto.go
  resp/responses/configurations/microphone.yaml
Labels: stationxml, debt

#1722 update manufacturer (Make) Sercel
  assets/dataloggers.csv
  assets/sensors.csv
  install/components.csv
  install/sensors.csv
  tools/impact/testdata/install/sensors.csv
  tools/stationxml/testdata/install/sensors.csv
Labels: stationxml

#1727 update auto generated descriptions
  resp/auto.go
  resp/generate/datalogger.go
  resp/generate/sensor.go
  tools/stationxml/testdata/test.xml
Labels: stationxml, maintenance
