Repository GeoNet/delta, pull requests merged in 2023-06, with the labels that each got.

#1725 update stationxml configuring of equipment details
  cmd/stationxml-build/main.go
  internal/stationxml/decoder10.go
  internal/stationxml/decoder11.go
  internal/stationxml/decoder12.go
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
  meta/channel.go
  meta/component.go
Labels: enhancement, stationxml

#1735 update manufacturer (Make) of remaining companies
  assets/dataloggers.csv
  assets/sensors.csv
  install/sensors.csv
Labels: stationxml

#1738 update manufacturer (Make) Paroscientific to SAIC
  assets/recorders.csv
  install/channels.csv
  install/components.csv
  install/firmware.csv
  install/recorders.csv
  resp/responses/dataloggers/saic.yaml
  resp/responses/sensors/saic.yaml
Labels: stationxml

#1739 update manufacturer (Make) PEL
  assets/dataloggers.csv
  assets/recorders.csv
  install/dataloggers.csv
  install/recorders.csv
Labels: stationxml

#1756 fix(spell): update network
  network/networks.csv
Labels: bug

#1755 refactor(headers): add headers to network tables
  meta/antenna.go
  meta/asset.go
  meta/calibration.go
  meta/camera.go
  meta/channel.go
  meta/citation.go
  meta/component.go
  meta/connection.go
  meta/constituent.go
  meta/datalogger.go
  meta/doas.go
  meta/feature.go
  meta/firmware.go
  meta/gain.go
  meta/gauge.go
  meta/mark.go
  meta/metsensor.go
  meta/monument.go
  meta/mount.go
  meta/network.go
  meta/placenames.go
  meta/polarity.go
  meta/preamp.go
  meta/radome.go
  meta/receiver.go
  meta/recorder.go
  meta/sample.go
  meta/sensor.go
  meta/session.go
  meta/site.go
  meta/station.go
  meta/streams.go
  meta/telemetry.go
  meta/view.go
  meta/visibility.go
Labels: debt

#1760 feat(stationxml): adding filter delay/corrections off by default
  cmd/stationxml-build/build.go
  cmd/stationxml-build/main.go
Labels: enhancement, stationxml
