Repository GeoNet/delta, pull requests merged in 2023-08, with the labels that each got.

#1803 feat: add response for basalt at 1hz sampling
  resp/auto.go
  resp/auto/datalogger_Kinemetrics_Basalt_26bits_1s.xml
  resp/responses/configurations/strongmotion.yaml
  resp/responses/dataloggers/kinemetrics.yaml
Labels: enhancement

#1809 fix: apply goimports to code base, manually fixed
  internal/stationxml/decoder10.go
  internal/stationxml/decoder11.go
  internal/stationxml/decoder12.go
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
  resp/generate/a2d.go
  resp/generate/fir.go
  resp/generate/paz.go
  resp/generate/polynomial.go
  resp/generate/stationxml.go
  tools/gloria/main.go
  tools/sit/main.go
Labels: maintenance

#1807 fix: removed the tool/sit debug code which was breaking the linter
  tools/sit/main.go
Labels: bug, debt

#1808 fix: bug with testing responses and do a double encode check
  resp/resp_test.go
Labels: bug

#1811 fix: update build workflow
  .github/workflows/build.yml
Labels: enhancement

#1817 fix: update the way the stationxml networks get their start/end times
  cmd/stationxml-build/main.go
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
  internal/stationxml/root.go
Labels: enhancement

#1818 feat: extend matcher to negative checks
  cmd/stationxml-build/matcher.go
  cmd/stationxml-build/matcher_test.go
Labels: enhancement

#1819 feat: switch to using a settings structure
  cmd/stationxml-build/main.go
Labels: enhancement

#1820 feat: add operational checks
  cmd/stationxml-build/main.go
Labels: enhancement

#1822 fix: update stationxml single file build parameters
  cmd/stationxml-build/main.go
  internal/stationxml/root.go
Labels: bug, enhancement

#1825 chore: remove sit trigger
  run/deploy/10-sit-trigger.sh
Labels: debt

#1826 fix: with connections ignore streams for recorder installed sensors
  meta/collection.go
Labels: bug

#1746 geomag: update EYWM coordinates
  network/stations.csv
Labels: geomag
