Repository GeoNet/delta, pull requests merged in 2024-12, with the labels that each got.

#2306 VGTR - Receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2310 ORRG - New GNSS Site
  assets/receivers.csv
  environment/visibility.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2311 MWOR - New GNSS site
  assets/receivers.csv
  environment/visibility.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2320 OHIN - receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2319 GIST - sensor swap - druck for druck
  assets/sensors.csv
  install/sensors.csv
Labels: tsunami

#2301 feat: update site end times to match station end times
  network/sites.csv
  network/stations.csv
Labels: maintenance
