Repository GeoNet/delta, pull requests merged in 2024-11, with the labels that each got.

#2266 PORA - Receiver Upgrade - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2279 VGOB Receiver Upgrade - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2281 MING Receiver Swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2284 feat: add ability to list response files
  resp/resp.go
Labels: enhancement, stationxml

#2288 feat: extend CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement

#2283 DBHI New GNSS Site - Alloy and Zephyr 3
  assets/receivers.csv
  environment/visibility.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2285 Fixing small issue in install/antennas.csv
  install/antennas.csv
Labels: gnss

#2290 PALI Receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2294 feat: update consistency checks
  tests/consistency_test.go
Labels: maintenance

#2296 feat: update doases consistency checks
  install/doases.csv
  tests/consistency_test.go
Labels: maintenance

#2295 feat: update consistency checks for monuments
  network/monuments.csv
  tests/consistency_test.go
Labels: maintenance
