Repository GeoNet/delta, pull requests merged in 2024-09, with the labels that each got.

#2209 fix: update STS-6A response
  resp/files/sensor_Streckeisen_STS-6A.xml
Labels: bug

#2213 feat: add SNZO to sensor config
  cmd/sensor-config/main.go
Labels: enhancement

#2215 feat: bump go version to 1.22
  go.mod
Labels: enhancement

#2186 DART NZF,G,H,I BPR End times
  environment/gauges.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart
