Repository GeoNet/delta, pull requests merged in 2024-06, with the labels that each got.

#2063 chore: add a tide-config application to replace tide
  cmd/tide-config/main.go
  cmd/tide-config/testdata/depth.out
  cmd/tide-config/testdata/depth.tmpl
  cmd/tide-config/testdata/detide.out
  cmd/tide-config/testdata/detide.tmpl
  cmd/tide-config/testdata/environment/constituents.csv
  cmd/tide-config/testdata/environment/gauges.csv
  cmd/tide-config/testdata/install/channels.csv
  cmd/tide-config/testdata/install/components.csv
  cmd/tide-config/testdata/install/connections.csv
  cmd/tide-config/testdata/install/dataloggers.csv
  cmd/tide-config/testdata/install/recorders.csv
  cmd/tide-config/testdata/install/sensors.csv
  cmd/tide-config/testdata/install/streams.csv
  cmd/tide-config/testdata/network/sites.csv
  cmd/tide-config/testdata/network/stations.csv
  cmd/tide-config/tide.go
  cmd/tide-config/tide_test.go
Labels: debt

#2066 chore: update sensor config
  cmd/sensor-config/envirosensor.go
  cmd/sensor-config/gnss.go
  cmd/sensor-config/installed.go
  cmd/sensor-config/manualcollect.go
  cmd/sensor-config/mount.go
  cmd/sensor-config/network.go
Labels: enhancement

#2068 chore: update sensor xml to add types at the sensor level
  cmd/sensor-config/envirosensor.go
  cmd/sensor-config/gnss.go
  cmd/sensor-config/installed.go
  cmd/sensor-config/mount.go
Labels: enhancement

#2070 bug: update spelling
  cmd/chart-config/config.go
  cmd/chart-config/main.go
Labels: bug

#2073 fix: update auto set code generation to improve application speed
  meta/generate/generate.go
  meta/set_auto.go
Labels: debt

#2072 chore: remove tides module
  README.md
  tides/README.md
  tides/auto.go
  tides/generate/main.go
  tides/tides.go
  tides/tides_test.go
Labels: debt

#2077 chore: remove unused sc3 applications
  tools/caps/main.go
  tools/caps/station_test.go
  tools/sc3/autopick.go
  tools/sc3/autopick_test.go
  tools/sc3/global.go
  tools/sc3/global_test.go
  tools/sc3/main.go
  tools/sc3/profile.go
  tools/sc3/station.go
  tools/sc3/station_test.go
Labels: debt

#2080 fix: update the test script
  test.sh
Labels: bug

#2085 chore: update geomag config to use resp
  cmd/geomag-config/main.go
Labels: debt

#2082 chore: remove the altus config app
  docs/instruments/Kinemetrics-Altus.md
  tools/altus/altus_test.go
  tools/altus/build.go
  tools/altus/main.go
  tools/altus/slates.go
  tools/altus/testdata/altus.xml
  tools/altus/testdata/install/connections.csv
  tools/altus/testdata/install/dataloggers.csv
  tools/altus/testdata/install/recorders.csv
  tools/altus/testdata/install/sensors.csv
  tools/altus/testdata/install/streams.csv
  tools/altus/testdata/network/networks.csv
  tools/altus/testdata/network/sites.csv
  tools/altus/testdata/network/stations.csv
Labels: debt

#2081 chore: remove the cusp config app
  docs/instruments/CSI-CUSP.md
  tools/cusp/build.go
  tools/cusp/cusp_test.go
  tools/cusp/main.go
  tools/cusp/testdata/cusp.xml
  tools/cusp/testdata/install/connections.csv
  tools/cusp/testdata/install/recorders.csv
  tools/cusp/testdata/install/streams.csv
  tools/cusp/testdata/network/networks.csv
  tools/cusp/testdata/network/stations.csv
Labels: debt

#2086 fix: update chart config to use resp
  cmd/chart-config/response.go
Labels: debt

#2084 chore: replace response type in stationxml with resp module
  cmd/stationxml-build/build.go
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
  internal/stationxml/root.go
  resp/response_type.go
Labels: debt

#2091 chore: remove tide tool
  tools/tide/main.go
Labels: debt

#2090 chore: remove impact tool
  tools/impact/README.md
  tools/impact/build.go
  tools/impact/impact_test.go
  tools/impact/main.go
  tools/impact/testdata/impact.json
  tools/impact/testdata/install/connections.csv
  tools/impact/testdata/install/dataloggers.csv
  tools/impact/testdata/install/recorders.csv
  tools/impact/testdata/install/sensors.csv
  tools/impact/testdata/install/streams.csv
  tools/impact/testdata/network/networks.csv
  tools/impact/testdata/network/sites.csv
  tools/impact/testdata/network/stations.csv
Labels: debt

#2092 chore: remove metadb module
  internal/metadb/calibrations.go
  internal/metadb/channels.go
  internal/metadb/connections.go
  internal/metadb/constituents.go
  internal/metadb/dataloggers.go
  internal/metadb/gains.go
  internal/metadb/gauges.go
  internal/metadb/installation.go
  internal/metadb/metadb.go
  internal/metadb/networks.go
  internal/metadb/recorders.go
  internal/metadb/sensors.go
  internal/metadb/sites.go
  internal/metadb/stations.go
  internal/metadb/streams.go
Labels: debt

#2100 feat: add geographical details to geomag config
  cmd/geomag-config/config.go
  cmd/geomag-config/main.go
Labels: enhancement

#2102 fix: switch to use camera group
  cmd/sensor-config/main.go
  cmd/sensor-config/mount.go
  cmd/sensor-config/settings.go
Labels: enhancement

#2107 Closing NZG site 41
  environment/gauges.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2110 fix: update tilde config to update site times instead of station times
  cmd/tilde-config/coastal.go
  cmd/tilde-config/dart.go
  cmd/tilde-config/envirosensor.go
  cmd/tilde-config/geomag.go
Labels: bug

#2123 feat: add ability to skip seiscomp streams
  cmd/sc3-config/main.go
  cmd/sc3-config/station.go
Labels: enhancement
