Repository GeoNet/delta, pull requests merged in 2024-04, with the labels that each got.

#2025 Westmelton2 GeoMag equipment update
  assets/dataloggers.csv
  install/connections.csv
  install/dataloggers.csv
  install/gains.csv
  install/sensors.csv
  install/streams.csv
  network/sites.csv
  network/stations.csv
Labels: geomag

#2018 fix: update dart response to include fake stage
  meta/collection.go
  resp/files/combined_SAIC_BPR-Subsystem_BPR-Subsystem_Z_15s.xml
  resp/files/combined_SAIC_BPR-Subsystem_BPR-Subsystem_Z_900s.xml
Labels: dart

#2029 chore: update features tests to handle scandoas
  tests/features_test.go
Labels: enhancement

#2032 fix: update geomag calibration info
  install/calibrations.csv
Labels: geomag
