Repository GeoNet/delta, pull requests merged in 2024-07, with the labels that each got.

#2114 Closing NZI site 41
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2124 Closing NZF site 42 Version 2!
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2078 feat: update polynomial coefficents to no longer be numbered
  internal/stationxml/encoder10.go
  internal/stationxml/encoder11.go
  internal/stationxml/encoder12.go
Labels: enhancement

#2127 NZH Site 42 opening
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2128 NZI Site 42 Reopening & updating Site 41 closure
  assets/recorders.csv
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2129 NZF Site 43 Opening and Site 42 closing update
  environment/gauges.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2131 chore: remove legacy parts to sensor-config
  cmd/sensor-config/dart.go
  cmd/sensor-config/envirosensor.go
  cmd/sensor-config/gnss.go
  cmd/sensor-config/installed.go
  cmd/sensor-config/main.go
  cmd/sensor-config/manualcollect.go
  cmd/sensor-config/mount.go
  cmd/sensor-config/settings.go
Labels: debt

#2140 feat: update visibility table to use Mark label
  environment/README.md
  environment/visibility.csv
  meta/list_test.go
  meta/testdata/visibility.csv
  meta/visibility.go
Labels: debt
