Repository GeoNet/delta, pull requests merged in 2025-05, with the labels that each got.

#2429 fix: update sensor config
  cmd/sensor-config/mount.go
Labels: bug

#2433 nfc: WKMT - Whakamoenga - New Tsunami Gauge site
  assets/dataloggers.csv
  assets/sensors.csv
  install/connections.csv
  install/dataloggers.csv
  install/firmware.csv
  install/sensors.csv
  install/streams.csv
  network/sites.csv
  network/stations.csv
Labels: tsunami

#2439 nfc: PGKH receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2444 feat: add coastal-config app
  cmd/coastal-config/README.md
  cmd/coastal-config/config.go
  cmd/coastal-config/detide.go
  cmd/coastal-config/main.go
Labels: tsunami

#2443 nfc: MKP1 - Opening new landlslide gnss site
  environment/visibility.csv
  install/antennas.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2445 nfc: MKP2 - Opening new landlslide gnss site
  environment/visibility.csv
  install/antennas.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2457 feat: update guralp sensor name
  assets/dataloggers.csv
  assets/sensors.csv
  install/components.csv
  install/sensors.csv
  resp/auto/sensor_Guralp_CMG-3TB_GN.xml
Labels: stationxml

#2327 fix: update the table building
  cmd/deltadb/main.go
  delta.go
  delta_test.go
  meta/delta.svg
  meta/sqlite/camera.go
  meta/sqlite/db.go
  meta/sqlite/receiver.go
  meta/sqlite/reference.go
  meta/sqlite/sensor.go
  meta/sqlite/station.go
  meta/sqlite/table.go
  tests/sqlite_test.go
Labels: bug

#2297 feat: updated channel and component consistency checks
  install/channels.csv
  install/components.csv
  tests/consistency_test.go
Labels: maintenance

#2298 feat: update antenna and session consistency checks
  install/antennas.csv
  install/sessions.csv
  tests/consistency_test.go
Labels: maintenance

#2460 fix: update notes network
  environment/notes.csv
Labels: bug

#1752 feat(notes): add a environment notes table
  cmd/deltadb/README.md
  environment/notes.csv
  meta/delta.svg
  meta/generate/main.go
  meta/note.go
  meta/note_test.go
  meta/set.go
  meta/set_auto.go
  meta/sqlite/db.go
  meta/sqlite/station.go
  meta/table.go
  meta/testdata/notes.csv
  tests/consistency_test.go
  tests/notes_test.go
Labels: enhancement

#2462 nfc: Closing NZJ site 41
  environment/gauges.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2463 feat: add reference table to sqlite db
  cmd/deltadb/README.md
  cmd/deltadb/delta.svg
  meta/delta.svg
  meta/sqlite/db.go
  meta/sqlite/gauge.go
  meta/sqlite/mark.go
  meta/sqlite/mount.go
  meta/sqlite/network.go
  meta/sqlite/reference.go
  meta/sqlite/sensor.go
  meta/sqlite/station.go
  meta/sqlite/table.go
Labels: enhancement
