Repository GeoNet/delta, pull requests merged in 2025-01, with the labels that each got.

#2323 feat: update golang to version 1.23
  go.mod
  go.sum
  tests/classes_test.go
  tests/connections_test.go
  tests/darts_test.go
  tests/gauges_test.go
  tests/marks_test.go
  tests/monuments_test.go
  tests/networks_test.go
  tests/sessions_test.go
  tests/sites_test.go
  tests/stations_test.go
  tests/streams_test.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/flags/flags.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go111.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go112.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/convert_map.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/modernc.org/memory/AUTHORS
  vendor/modernc.org/memory/CONTRIBUTORS
  vendor/modernc.org/memory/mmap_windows.go
  vendor/modules.txt
Labels: maintenance

#2324 fix: rename Reftek to RefTek
  assets/dataloggers.csv
Labels: maintenance

#2325 fix: adjust mount and station times
  network/mounts.csv
  network/stations.csv
Labels: maintenance

#2326 fix: adjust camera view and installation times
  install/cameras.csv
  network/views.csv
Labels: maintenance

#2305 feat: update sqlite to use a hand build schema
  cmd/deltadb/README.md
  cmd/deltadb/handler.go
  cmd/deltadb/main.go
  cmd/deltadb/mark.go
  cmd/deltadb/monument.go
  cmd/deltadb/network.go
  cmd/deltadb/sample.go
  cmd/deltadb/sensor.go
  cmd/deltadb/site.go
  cmd/deltadb/station.go
  meta/README.md
  meta/delta.svg
  meta/placenames.go
  meta/sqlite/asset.go
  meta/sqlite/camera.go
  meta/sqlite/database.go
  meta/sqlite/db.go
  meta/sqlite/gauge.go
  meta/sqlite/mark.go
  meta/sqlite/monument.go
  meta/sqlite/mount.go
  meta/sqlite/network.go
  meta/sqlite/point.go
  meta/sqlite/receiver.go
  meta/sqlite/reference.go
  meta/sqlite/response.go
  meta/sqlite/sample.go
  meta/sqlite/sensor.go
  meta/sqlite/site.go
  meta/sqlite/sql.go
  meta/sqlite/sqlite-schema-diagram.sql
  meta/sqlite/station.go
  meta/sqlite/table.go
  meta/table.go
  tests/sqlite_test.go
Labels: enhancement

#2330 PUKE Receiver swap - NetR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss
