Repository GeoNet/delta, pull requests merged in 2025-06, with the labels that each got.

#2465 fix: update gauge sqlite table
  cmd/deltadb/delta.svg
  meta/sqlite/gauge.go
Labels: bug

#2458 nfc: PUYT - datalogger swap - Q330s/3 for Centaur
  assets/dataloggers.csv
  install/dataloggers.csv
  install/firmware.csv
Labels: tsunami

#2468 nfc: NZJ site 42 - redeployment
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2469 nfc: Closing NZL site 41
  environment/gauges.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2473 nfc: Opening NZL site 42 - redeployment
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2474 nfc: Opening NZK site 42 - redeployment
  assets/recorders.csv
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2476 nfc: Closing NZD site 41
  environment/gauges.csv
  install/firmware.csv
  install/recorders.csv
  install/streams.csv
  network/sites.csv
Labels: dart

#2479 Fix ASBS wrong Longitude
  network/stations.csv
Labels: bug
