Repository GeoNet/delta, pull requests merged in 2025-07, with the labels that each got.

#2485 nfc: ERWO - New GNSS site setup
  assets/antennas.csv
  assets/receivers.csv
  environment/visibility.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
  network/marks.csv
  network/monuments.csv
Labels: gnss

#2487 fix: updated second version
  resp/auto/sensor_Nanometrics-Inc_Trillium-Compact-20PH-2.xml
Labels: bug

#2493 feat: add GT network to sensor config
  cmd/sensor-config/main.go
Labels: bug

#2492 nfc: JBTT - New Tsunami Gauge
  assets/dataloggers.csv
  assets/sensors.csv
  install/connections.csv
  install/dataloggers.csv
  install/firmware.csv
  install/sensors.csv
  install/streams.csv
  network/sites.csv
  network/stations.csv
Labels: tsunami

#2494 nfc: RGAR receiver swap - NetR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2495 nfc: SCTY - Receiver and Antenna swap
  assets/antennas.csv
  assets/receivers.csv
  install/antennas.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2500 fix: update camera install test
  tests/cameras_test.go
Labels: bug

#2503 fix: avoid multiple volcam images per endpoint
  cmd/volcam-config/main.go
Labels: bug

#2504 nfc: TGWH - NETR9 to Alloy Receiver swap
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2467 nfc: update borehole orientations
  install/sensors.csv
Labels: enhancement

#2506 nfc: VGPK receiver swap - NetR9 to Alloy
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2512 nfc: DURV receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2513 nfc: TORY Receiver swap - NETR9 to Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
  install/sessions.csv
Labels: gnss

#2517 nfc: PARW Receiver swap - Alloy for Alloy
  assets/receivers.csv
  install/firmware.csv
  install/receivers.csv
Labels: gnss
